
version: '2'
services:
  spark-master:
    image: jupyter/pyspark-notebook
    ports:
      - 7077:7077
      - 8080:8080
      - 6066:6066
    command: ["/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]

  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
    volumes:
      - ./app/src:/home/jovyan/src
      - ./app/work:/home/jovyan/work
      - ./app/data:/home/jovyan/data

  spark-worker:
    # Example for starting and connecting worker to spark master
    image: jupyter/pyspark-notebook
    volumes:
      - ./worker:/scratch
    environment:
      - SPARK_WORKER_DIR=/scratch
    command: ["/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    depends_on:
      - spark-master
