
version: '2'
services:
  spark:
    container_name: dis_spark
    image: bitnami/spark:2
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 7077:7077
      - 8080:8080
      - 6066:6066
#    command: ["/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    volumes:
      - ./app/src:/app/src
      - ./app/data:/app/data
      - ./app/.models:/app/.models
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - backend

  spark-worker-1:
    image: bitnami/spark:2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./app/src:/app/src
      - ./app/data:/app/data
      - ./app/.models:/app/.models
    depends_on:
      - spark
      - mongodb
    links:
      - mongodb
    networks:
      - backend

  jupyter:
    container_name: dis_jupyter
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
    volumes:
      - ./app/work:/home/jovyan/work
      - ./app/data:/home/jovyan/data
      - ./app/.models:/home/jovyan/.models
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - backend

  mongodb:
    container_name: dis_mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27018:27017
    expose:
      - 27017
    volumes:
      - ./app/.mongodb:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

#volumes:
#  mongodb_data_container:
