path:
  data:
    in: /app/data/data-in
    attrs: /app/data/meta/attributes.csv
    models: /app/.models

database:
  name: smartphone_activity
  table:
    data_in: data_in
    results: results

  mongodb:
    credentials: root:password@mongodb
    port: 27017

  textdb:
    format: json
    path: /app/.textdb

