path:
  data:
    in: data/data-in
    models: .models
mongodb:
  credentials: root:password@mongodb
  port: 27017
  database:
    name: smartphone_activity
    table:
      data_in: data_in
      results: results